name: Branch Name Check
run-name: ${{ github.actor }} Checking branch name on create
on:
  create:
    branches:
      - '*'

jobs:
  Check-Branch-Name:
    runs-on: ubuntu-latest
    steps:
      - run: apt-get install jq -y
      - name: Get GitHub Bio
        id: get_github_bio
        run: |
          id_git=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/users/${{ github.actor }} \
          | jq -r '.bio'); \
          echo "bio=$id_git" >> $GITHUB_OUTPUT
          

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - run: echo "🍏 This branch name is ${{ steps.extract_branch.outputs.branch }}."
      - name: Check branch name
        id: check-branch_name
        run: |
          if echo "${{ steps.extract_branch.outputs.branch }}" | grep -Po '^(chore|feat|fix|hotfix)/[a-zA-Z0-9-]+/(RM|GH)-\d{6}_[a-zA-Z0-9-]+$'; then
              echo "match=true" >> $GITHUB_OUTPUT
          fi
      - name: Exit Status Update
        if: steps.check-branch_name.outputs.match != 'true'
        run: |
          exit1
          

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notification_title: "Nom de branche mal formaté"
          notify_when: 'failure'
          mention_users: ${{ steps.get_github_bio.outputs.bio }}
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}@{branch}> on <{commit_url}|{commit_sha}>  
          \n Merci de consulter la documentation pour le formatage des noms de branche : https://github.com/UlysseCarpentier/GHActions-Git-Brother"
          footer: "<{run_url}|View Run>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
