name: Test refs
on:
  push:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo
        run: |
          echo ${GITHUB_REF}
          echo ${GITHUB_REF#refs/heads/}
          echo ${{ github.ref_name }}
