name: Automerge
# Git App Rights (Repo):
# Contents write
# Pull requests write
# Workflows write

# OPTIONAL Create ruleset protection repo-sync/comments for bot-repo Pull request without review
on:
  workflow_dispatch:
  pull_request:
    types: [opened]
jobs:
  sync_files:
    runs-on: ubuntu-latest
    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}
          permissions: >-
            {
              "contents": "write",
              "metadata": "read",
              "pull_requests": "write",
              "workflows": "write"
            }
      - run: "echo 'The created token is masked: ${{ steps.create_token.outputs.token }}'"
      - name: Checkout Repository
        id: checkout_branch
        uses: actions/checkout@v3

      - name: Pull Request Automerge
        run: |
          gh pr merge --squash --auto ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ steps.create_token.outputs.token }}
        ####
        ####ICI trigger pull request du bot et auto review/merge
      - name: Approve pull request
        uses: andrewmusgrave/automatic-pull-request-review@0.0.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          event: APPROVE
          body: 'Thank you dependabot 🎊'

